project:
  title: "Slides"
  output-dir: _output
  execute-dir: project
  render:
    - "*.qmd"
    - "!README.md"

format: 
  revealjs:
    theme: blood
    slide-level: 2
    hash-type: number
    embed-resources: true
    show-notes: true
  pptx: default
  docx:
    toc: false